experiment: asrinit_lr1e-5_fp32_properval
model_name_or_path: facebook/wav2vec2-base-960h
train_setting: asr_initialized_properval
train_shards:
  - data/train/shard-000000.tar
  - data/train/shard-000001.tar
  - data/train/shard-000002.tar
  - data/train/shard-000003.tar
eval_shards:
  - data/train/shard-000004.tar
final_test_clean_shards: data/test-clean
final_test_other_shards: data/test-other
learning_rate: 1.0e-5
fp16_training: false
loss_impl: hf
disable_spec_augment: true
ctc_zero_infinity: true
no_attention_mask_for_loss: true
freeze_setting: none
layerwise_lr_decay: false
decoding_method: greedy
